version: '3'

services:
  db:
    image: postgres:9.5-alpine
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: drchrono
    logging:
      driver: none

  client:
    build:
      context: .
    ports:
      - "3000:8000"
    volumes:
      - ./drchrono:/app
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    working_dir: /app
    environment:
      ENV_NAME: Development
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_HOST: db
      PG_PORT: 5432
      PG_DB: drchrono
      DJANGO_SETTINGS_MODULE: 'application.settings.local_dev'
    links:
      - db
    depends_on:
      - db
