version: '3'

services:
  db:
    image: postgres:9.5-alpine
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: drchrono
    logging:
      driver: none

  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"

  client:
    build:
      context: .
    ports:
      - "3000:8000"
    volumes:
      - ./drchrono:/app
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      DJANGO_SETTINGS_MODULE: application.settings.local_dev
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_HOST: db
      PG_PORT: 5432
      PG_DB: drchrono
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SOCIAL_AUTH_DRCHRONO_KEY: fake_key
      SOCIAL_AUTH_DRCHRONO_SECRET: fake_secret
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
