# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.6
        environment:
          DJANGO_SETTINGS_MODULE: application.settings.base
          PG_USER: ubuntu
          PG_PASSWORD: ""
          PG_HOST: localhost
          PG_PORT: 5432
          PG_DB: drchrono
          SOCIAL_AUTH_DRCHRONO_KEY: fake_key
          SOCIAL_AUTH_DRCHRONO_SECRET: fake_secret
          
      - image: circleci/9.6
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: drchrono
          POSTGRES_PASSWORD: ""

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
          